services:
  dagster:
    container_name: dagster
    build:
      context: .
      dockerfile: og_dagster/Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./og_dagster:/app
      - ./dbt_project:/app/dbt_project
      - ./duckdb:/data/duckdb
      - ./raw_data:/app/raw_data
    environment:
      - DAGSTER_HOME=/app
      - DATABASE_URL="${DATABASE_URL}"
      - DUCKDB_CACHE_PATH=/data/duckdb/local.duckdb

    env_file:
      - .env
    command:
      - dagster
      - dev
      - '-h'
      - 0.0.0.0
      - '-p'
      - '3000'
      - '-w'
      - workspace.yaml

  dagster-readonly:
    container_name: dagster-readonly
    build:
      context: .
      dockerfile: og_dagster/Dockerfile
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - ./og_dagster:/app
      - ./dbt_project:/app/dbt_project
      - ./duckdb:/data/duckdb
      - ./raw_data:/app/raw_data
    environment:
      - DAGSTER_HOME=/app
      - DATABASE_URL="${DATABASE_URL}"
      - DUCKDB_CACHE_PATH=/data/duckdb/local.duckdb
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - |
        echo "=================================================="
        echo "🚀 Dagster webserver starting...in 2mins. Note: Port mapped 3001:3000"
        echo "📊 Access it at: http://localhost:3001"
        echo "=================================================="
        exec dagster-webserver --read-only -h 0.0.0.0 -p 3000 -w workspace.yaml

  dlt:
    container_name: dlt
    build:
      context: ./dlt_pipelines
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./dlt_pipelines:/app
      - ./duckdb:/data/duckdb
    environment:
      - DUCKDB_CACHE_PATH=/data/duckdb/local.duckdb
      - DATABASE_URL="postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require"
      

    env_file:
      - .env
    command:
      - python
      - loaders/privote_loader.py

  dbt:
    container_name: dbt
    build:
      context: ./dbt_project
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./dbt_project:/app
      - ./duckdb:/data/duckdb
    env_file:
      - .env
    environment:
      - DBT_TARGET=prod_postgres
    entrypoint:
      - dbt
    working_dir: /app

volumes:
  duckdb: null
