# dbt_project/dbt_project.yml
name: opengrants
version: 1.0.0
profile: opengrants
config-version: 2

model-paths: [ "models" ]

models:
  +materialized: view
  gold:
    +materialized: table
    +depends_on:
    - ref('gold__all_projects')
    - ref('gold__all_grant_pools')
