# dbt_project/dbt_project.yml
name: opengrants
version: 1.0.0
profile: opengrants
config-version: 2

model-paths: [ "models" ]

models:
  opengrants:
    +materialized: view
    gold:
      +materialized: table
      +tags: ["gold"]
