# /home/torch/opengrants-platform/dbt_project/models/sources.yml
version: 2

sources:
  - name: silver
    schema: public
    tables:
      - name: silver_giveth_projects
      - name: silver_giveth_grant_pools
      - name: silver_scf_projects
      - name: silver_scf_grant_pools
      - name: silver_scf_grant_applications
      - name: silver_privote_projects
      - name: silver_privote_grant_pools
      - name: silver_privote_grant_applications
      # GrantStack (Gitcoin Grants Stack)
      - name: silver_grantsstack_grant_pools
      - name: silver_grantsstack_projects
      - name: silver_grantsstack_grant_applications
      - name: silver_grantsstack_donations
      - name: silver_grantsstack_payouts